### ISSUE TITLE
Sequencer Authentication

### ISSUE THREAD

**Issue by avalonche** [flashbots/op-geth#14]
Authenticate the sequencer request to get payload on the builder.

**Comment by dmarzzz** [comment]
> I would keep it simple for now, preconfigure the sequencer signing address on the block builder CLI configuration side, and then make some minimal modification to the op-node sequencer, to sign their block-builder request with the unsafe-block signing key.

**Comment by dmarzzz** [comment]
> We could make this an array to store a backup key somewhere in event the sequencer needs to switch quickly, but after talking to some L2s they said they have never had to change and if they did it, it would incur down time anyways.
